name: build-check
run-name: ${{ github.actor }} running build check on MR/PR to main
on:
    pull_request:
        branches: [main, staging]
jobs:
    production-build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout main
              uses: actions/checkout@v4
              with:
                  ref: main
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.8.*"
            - name: Update NPM version
              run: npm i -g npm@latest
            - name: Install dependencies
              run: npm ci
            - name: Run build check
              run: npm run build

    staging-build:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging'
        steps:
            - name: Checkout staging
              uses: actions/checkout@v4
              with:
                  ref: staging
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.8.*"
            - name: Update NPM version
              run: npm i -g npm@latest
            - name: Install dependencies
              run: npm ci
            - name: Run build check
              run: npm run build
